name: Waka Readme

on:
  workflow_dispatch: # for manual workflow trigger
  schedule:
    - cron: "0 0 * * *" # runs at every 12AM UTC

jobs:
  update-readme:
    name: Lilac
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          # following flags are required, only if this is not on
          # profile readme, remove the leading `#` to use them
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPOSITORY: Qoiuy/Qoiuy
          BLOCKS: ░▒▓█
          TIME_RANGE: last_7_days
          # SECTION_NAME: qoiuy
